---

- name: create database
  mysql_db: >
    name="{{ project.database}}"
    login_user="{{ user }}"
    state=present
  tags: db_mysql

- name: backup database
  shell: "mysqldump {{ project.database }} | gzip > {{ project_base_dir }}/backup/db/{{ project.database }}-$(date +%Y-%m-%d-%H%M%S).sql.gz"
  tags: db_mysql