# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='min_rate',
            field=models.SmallIntegerField(default=0),
        ),
    ]
