---

- name: Install packages
  apt: >
    update_cache=yes
    name={{ item }}  state=present
  with_items:
    - python-dev
    - python-pip
    - python-tk
    - python-boto
  become: yes
  become_user: root
  tags: python2

- name: Download && Unpack Python-2.7.12
  unarchive: >
    src=https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz
    dest="{{ project_base_dir }}"
    copy=no
  tags: python2

- name: Install Python-2.7.12
  shell: "{{ item }} chdir={{ project_base_dir }}/Python-2.7.12"
  with_items:
    - ./configure
    - /usr/bin/make
    - /usr/bin/make install
  become: yes
  become_user: root 
  tags: python2


- name: rm directory
  file: >
    path="{{ project_base_dir }}/Python-2.7.12"
    state=absent
  become: yes
  become_user: root
  tags: python2