---

- name: Install base packages
  apt: >
    update_cache=yes
    name={{ item }}  state=present
  with_items:
    - bash 
    - libpam-systemd
    - vim
    - build-essential
    - curl 
    - git
    - htop 
    - libffi-dev 
    - libfreetype6-dev 
    - libjpeg-dev 
    - liblcms2-dev 
    - libpq-dev 
    - libssl-dev 
    - libssl-doc 
    - libtiff-dev 
    - libwebp-dev 
    - libxml2-dev 
    - libxslt1-dev 
    - openssl 
    - python-pycurl 
    - python-virtualenv 
    - tcl8.5-dev 
    - tk8.6-dev 
    - zlib1g-dev
  become: yes
  become_user: root 
  tags: system