---

- name: Install apache2 && wsgi-py3
  apt: >
    update_cache=yes
    name={{ item }}
    state=present
  with_items:
    - apache2
    - apache2-utils
    - libapache2-mod-wsgi-py3
  become: yes
  become_user: root
  tags: apache-install

- name: remove all from sites-enabled
  file: >
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  become: yes
  become_user: root
  tags: apache-install
