---

- name: create database
  postgresql_db: >
    name="{{ project.database}}"
    login_user="{{ user }}"
    state=present
  become: no
  tags: db_postgres

- name: backup database
  shell: "pg_dump --no-owner {{ project.database }} | gzip > {{ project_base_dir }}/backup/db/{{ project.database }}-$(date +%Y-%m-%d-%H%M%S).sql.gz"
  tags: db_postgres