---

- name: Add backports repository
  apt_repository: >
    repo="deb http://ftp.debian.org/debian jessie-backports main"
    state=present
    filename="jessie-backports"
  become: yes
  become_user: root
  tags: certbot_debian

- name: Install certbot
  apt: >
    name=certbot
    state=latest
    default_release=jessie-backports
    update_cache=yes
  become: yes
  become_user: root
  tags: certbot_debian

- name: Request signed certificate
  shell: "certbot certonly --webroot -w /usr/share/nginx/html/ --non-interactive  --agree-tos --email {{ certbot_email }} -d {{ server }}"
  become: yes
  become_user: root 
  tags: certbot_debian

